# Generated by Django 3.0.4 on 2020-03-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
