# Generated by Django 3.0.4 on 2020-03-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='community.Community'),
        ),
        migrations.AddField(
            model_name='location',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
