# Generated by Django 3.0.4 on 2020-03-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20200328_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
