# Generated by Django 3.0.4 on 2020-03-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20200328_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='population',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
