# Generated by Django 3.0.4 on 2020-03-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20200328_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='population',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
