# Generated by Django 3.0.4 on 2020-03-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='community_cases',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
